### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
@mauritsvanrees @jensens @ericof 

I would say this is ready for review and merge.

The changes here come from https://github.com/plone/meta/pull/1 (which has been rebased and refactored 😄 )

### CODE REVIEW

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Thanks!

I come to the same code when I try `plone/meta`, except a few small things you added manually, like ignoring `conf.py` in check-manifest.
`tox.ini` could be added to that list, but that is a minor point. Can be fixed in plone/meta first, and then we check if updating an already configured package is working nicely.

**Comment by gforcada** [comment]
Oh right, `check-manifest` has been a bit of an eyesore as of late to me, so we might better integrate it. `zest.releaser` pre-release command already runs all the nice things right? like `pyroma` and others, right? we might as well add it on the linting part, to ensure that whenever we are about to make a release, all PRs have left the repository in a releaseable state 😄

**Comment by mauritsvanrees** [comment]
Mostly `check-manifest` and `pyroma` yes.

We can't call `prerelease` itself, if that is what you want, because it will want to make a commit. We could add some support perhaps.

There is also [`python -m -r -s`](`https://stackoverflow.com/questions/30328259/what-does-python-setup-py-check-actually-do#30332432`). Needs `docutils` for full support.

**Pull request merged**
