### PR TITLE
Include request form parameters from parent request

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Review by jensens — APPROVED** [review]

**Comment by agitator** [comment]
@mauritsvanrees any idea why 5.2 fails?

I ran the tests locally with `ROBOT_BROWSER=chrome  ./bin/test --all -m plone.app.contenttypes` and had no issues

``` 
❯ ROBOT_BROWSER=chrome  ./bin/test --all -m plone.app.contenttypes
/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.robotframework-1.5.6-py2.7.egg/plone/app/robotframework/__init__.py:17: ImportWarning: Not importing directory '/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.robotframework-1.5.6-py2.7.egg/plone/app/robotframework/content': missing __init__.py
  from plone.app.robotframework.content import Content
/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.imaging-2.1.1-py2.7.egg/plone/app/imaging/__init__.py:2: DeprecationWarning: setDefaultRoles is deprecated. Please use addPermission from AccessControl.Permission.
  from Products.CMFCore.permissions import setDefaultRoles
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.Archetypes-1.16.3-py2.7.egg/Products/Archetypes/generator/widget.py:4: DeprecationWarning: InitializeClass is deprecated. Please import from AccessControl.class_init.
  from App.class_init import InitializeClass
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.Archetypes-1.16.3-py2.7.egg/Products/Archetypes/interfaces/event.py:4: DeprecationWarning: IObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import IObjectEvent
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.Archetypes-1.16.3-py2.7.egg/Products/Archetypes/ReferenceEngine.py:31: DeprecationWarning: LazyMap is deprecated. Please import from ZTUtils.Lazy.
  from Products.ZCatalog.Lazy import LazyMap
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.Archetypes-1.16.3-py2.7.egg/Products/Archetypes/mimetype_utils.py:9: DeprecationWarning: ComponentLookupError is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ComponentLookupError
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.Archetypes-1.16.3-py2.7.egg/Products/Archetypes/event.py:6: DeprecationWarning: ObjectEvent is deprecated. Import from zope.interface.interfaces
  from zope.component.interfaces import ObjectEvent
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.Marshall-2.4.1-py2.7.egg/Products/Marshall/handlers/atxml.py:53: ImportWarning: Not importing directory '/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.Marshall-2.4.1-py2.7.egg/Products/Marshall/utils': missing __init__.py
  from Products.Marshall import utils
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.ATContentTypes-3.0.4-py2.7.egg/Products/ATContentTypes/interfaces/factories.py:2: DeprecationWarning: IFileFactory is deprecated. Import IFileFactory from zope.filerepresentation.interfaces instead
  from plone.app.widgets.interfaces import IFileFactory
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.ATContentTypes-3.0.4-py2.7.egg/Products/ATContentTypes/permission.py:2: DeprecationWarning: IFieldPermissionChecker is deprecated. Import IFieldPermissionChecker from plone.app.z3cform.interfaces instead
  from plone.app.widgets.interfaces import IFieldPermissionChecker
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.ATContentTypes-3.0.4-py2.7.egg/Products/ATContentTypes/content/base.py:21: DeprecationWarning: ResourceLockedError is deprecated. Please import from zExceptions.
  from webdav.Lockable import ResourceLockedError
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.ATContentTypes-3.0.4-py2.7.egg/Products/ATContentTypes/lib/historyaware.py:4: DeprecationWarning: html_quote is deprecated. Please import from DocumentTemplate.html_quote. These shims will go away in DocumentTemplate 4.0.
  from DocumentTemplate.DT_Util import html_quote
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.ATContentTypes-3.0.4-py2.7.egg/Products/ATContentTypes/content/topic.py:35: DeprecationWarning: LazyCat is deprecated. Please import from ZTUtils.Lazy.
  from Products.ZCatalog.Lazy import LazyCat
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.ATContentTypes-3.0.4-py2.7.egg/Products/ATContentTypes/tool/factory.py:30: DeprecationWarning: call_object is deprecated. Please import from ZServer.ZPublisher.Publish.
  from ZPublisher.Publish import call_object
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.ATContentTypes-3.0.4-py2.7.egg/Products/ATContentTypes/tool/factory.py:31: DeprecationWarning: dont_publish_class is deprecated. Please import from ZServer.ZPublisher.Publish.
  from ZPublisher.Publish import dont_publish_class
/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.ATContentTypes-3.0.4-py2.7.egg/Products/ATContentTypes/tool/factory.py:32: DeprecationWarning: missing_name is deprecated. Please import from ZServer.ZPublisher.Publish.
  from ZPublisher.Publish import missing_name
/Users/peter/workspace/buildout.coredev52-py27/eggs/archetypes.schemaextender-3.0.1-py2.7.egg/archetypes/schemaextender/extender.py:15: DeprecationWarning: zope.site.hooks has moved to zope.component.hooks. Import of zope.site.hooks will become unsupported in Version 5.0
  from zope.site.hooks import getSite
/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.contenttypes-2.2.1-py2.7.egg/plone/app/contenttypes/migration/patches.py:13: DeprecationWarning: _marker is deprecated. Please import from Products.PluginIndexes.unindex.
  from Products.PluginIndexes.common.UnIndex import _marker
/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.blob-1.8.1-py2.7.egg/plone/app/blob/content.py:23: DeprecationWarning: MimeTypeException is deprecated. Import from Products.MimetypesRegistry.interfaces instead
  from Products.MimetypesRegistry.common import MimeTypeException
Running plone.app.contenttypes.testing.PloneAppContenttypes:Migration tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.zope.Startup in 0.268 seconds.
  Set up plone.app.testing.layers.PloneFixture /Users/peter/workspace/buildout.coredev52-py27/src/plone.app.upgrade/plone/app/upgrade/__init__.py:157: DeprecationWarning: GopipIndex is deprecated. Please import from plone.folder.nogopip
  from plone.app.folder.nogopip import GopipIndex
in 7.942 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypesMigration in 0.422 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes:Migration in 0.000 seconds.
  Running:
    49/99 (49.5%)/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.dexterity-2.10.0-py2.7.egg/plone/dexterity/schema.py:184: DeprecationWarning: No behavior registration found for behavior named "plone.app.contenttypes.interfaces.IEvent" for factory "Event" - trying deprecated fallback lookup (will be removed in 3.0)..."
  DeprecationWarning,
    58/99 (58.6%)/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.autoform-1.9.0-py2.7.egg/plone/autoform/base.py:247: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  message = e.message
    63/99 (63.6%)/Users/peter/workspace/buildout.coredev52-py27/eggs/Products.PortalTransforms-3.1.10-py2.7.egg/Products/PortalTransforms/libtransforms/commandtransform.py:88: DeprecationWarning: os.popen4 is deprecated.  Use the subprocess module.
  cin, couterr = os.popen4(command, 'b')
                  
  Ran 99 tests with 0 failures, 0 errors, 3 skipped in 31.856 seconds.
Running plone.app.contenttypes.testing.PloneAppContenttypes:Migration_Functional tests:
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes:Migration in 0.000 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes:Migration_Functional in 0.000 seconds.
  Running:
                  
  Ran 6 tests with 0 failures, 0 errors, 0 skipped in 5.653 seconds.
Running plone.app.contenttypes.testing.PloneAppContenttypes:Functional tests:
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes:Migration_Functional in 0.000 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypesMigration in 0.039 seconds.
  Set up plone.app.event.testing.PAEventLayer in 0.243 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes in 0.129 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes:Functional in 0.000 seconds.
  Running:
    5/49 (10.2%)/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.scale-3.1.2-py2.7.egg/plone/scale/scale.py:143: DeprecationWarning: the 'direction' option is deprecated, use 'mode' instead
  DeprecationWarning)
    49/49 (100.0%)/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.contenttypes-2.2.1-py2.7.egg/plone/app/contenttypes/tests/test_security.py:100: DeprecationWarning: Request is deprecated. Please import from ZPublisher.HTTPRequest
  from ZPublisher.Request import Request
/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.contenttypes-2.2.1-py2.7.egg/plone/app/contenttypes/tests/test_security.py:101: DeprecationWarning: Response is deprecated. Please import from ZPublisher.HTTPResponse
  from ZPublisher.Response import Response
/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.contenttypes-2.2.1-py2.7.egg/plone/app/contenttypes/tests/test_security.py:104: DeprecationWarning: publish_module is deprecated. Please import from ZServer.ZPublisher.Publish.
  from ZPublisher.Publish import publish_module
                  
  Ran 49 tests with 0 failures, 0 errors, 0 skipped in 21.126 seconds.
Running plone.app.contenttypes.testing.PloneAppContenttypes:Integration tests:
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes:Functional in 0.000 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes:Integration in 0.000 seconds.
  Running:
    6/122 (4.9%)/Users/peter/workspace/buildout.coredev52-py27/eggs/plone.app.contenttypes-2.2.1-py2.7.egg/plone/app/contenttypes/tests/test_collection.py:84: DeprecationWarning: getRawQuery() is deprecated; use getQuery().
  self.assertEqual(self.collection.getRawQuery(), query)
                    
  Ran 122 tests with 0 failures, 0 errors, 0 skipped in 14.433 seconds.
Running plone.app.contenttypes.tests.test_content_profile.PloneAppContenttypesContent:Integration tests:
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes:Integration in 0.000 seconds.
  Set up plone.app.contenttypes.tests.test_content_profile.PloneAppContenttypesContent in 0.451 seconds.
  Set up plone.app.contenttypes.tests.test_content_profile.PloneAppContenttypesContent:Integration in 0.000 seconds.
  Running:
                    
  Ran 16 tests with 0 failures, 0 errors, 3 skipped in 0.071 seconds.
Running plone.app.contenttypes.testing.PloneAppContenttypes:Robot tests:
  Tear down plone.app.contenttypes.tests.test_content_profile.PloneAppContenttypesContent:Integration in 0.000 seconds.
  Tear down plone.app.contenttypes.tests.test_content_profile.PloneAppContenttypesContent in 0.004 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes in 0.040 seconds.
  Set up plone.app.robotframework.remote.RemoteLibraryBundle:RobotRemote in 0.000 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypesRobot in 0.198 seconds.
  Set up plone.testing.zope.WSGIServer /Users/peter/workspace/buildout.coredev52-py27/eggs/waitress-1.4.4-py2.7.egg/waitress/adjustments.py:445: DeprecationWarning: In future versions of Waitress clear_untrusted_proxy_headers will be set to True by default. You may opt-out by setting this value to False, or opt-in explicitly by setting this to True.
  DeprecationWarning,
in 0.089 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes:Robot in 0.000 seconds.
  Running:
    1/16 (6.2%)/Users/peter/workspace/buildout.coredev52-py27/eggs/robotframework-3.1.2-py2.7.egg/robot/running/builder.py:62: DeprecationWarning: Option 'warn_on_skipped' is deprecated and has no effect.
  "effect.", DeprecationWarning)
/Users/peter/workspace/buildout.coredev52-py27/eggs/robotframework_seleniumlibrary-3.3.1-py2.7.egg/SeleniumLibrary/utils/deprecated.py:38: DeprecationWarning: "SeleniumLibrary._implicit_wait_in_secs" is deprecated, use "SeleniumLibrary.implicit_wait" instead.
  DeprecationWarning)
/Users/peter/workspace/buildout.coredev52-py27/eggs/robotframework_seleniumlibrary-3.3.1-py2.7.egg/SeleniumLibrary/utils/deprecated.py:38: DeprecationWarning: "SeleniumLibrary._run_on_failure_keyword" is deprecated, use "SeleniumLibrary.run_on_failure_keyword" instead.
  DeprecationWarning)
/Users/peter/workspace/buildout.coredev52-py27/eggs/robotframework_seleniumlibrary-3.3.1-py2.7.egg/SeleniumLibrary/utils/deprecated.py:38: DeprecationWarning: "SeleniumLibrary._speed_in_secs" is deprecated, use "SeleniumLibrary.speed" instead.
  DeprecationWarning)
/Users/peter/workspace/buildout.coredev52-py27/eggs/robotframework_seleniumlibrary-3.3.1-py2.7.egg/SeleniumLibrary/utils/deprecated.py:38: DeprecationWarning: "SeleniumLibrary._timeout_in_secs" is deprecated, use "SeleniumLibrary.timeout" instead.
  DeprecationWarning)
[ WARN ] Keyword 'Selenium2Library.Xpath Should Match X Times' is deprecated. Use `Page Should Contain Element` with ``limit`` argument instead.
/Users/peter/workspace/buildout.coredev52-py27/eggs/robotframework_seleniumlibrary-3.3.1-py2.7.egg/SeleniumLibrary/__init__.py:457: DeprecationWarning: "SeleniumLibrary._current_browser" is deprecated, use "SeleniumLibrary.driver" instead.
  DeprecationWarning)
    2/16 (12.5%)[ WARN ] Keyword 'Selenium2Library.Xpath Should Match X Times' is deprecated. Use `Page Should Contain Element` with ``limit`` argument instead.
    13/16 (81.2%)[ WARN ] Keyword 'Selenium2Library.Xpath Should Match X Times' is deprecated. Use `Page Should Contain Element` with ``limit`` argument instead.
    14/16 (87.5%)[ WARN ] Keyword 'Selenium2Library.Xpath Should Match X Times' is deprecated. Use `Page Should Contain Element` with ``limit`` argument instead.
    15/16 (93.8%)[ WARN ] Keyword 'Selenium2Library.Xpath Should Match X Times' is deprecated. Use `Page Should Contain Element` with ``limit`` argument instead.
    16/16 (100.0%)[ WARN ] Keyword 'Selenium2Library.Xpath Should Match X Times' is deprecated. Use `Page Should Contain Element` with ``limit`` argument instead.
                  
  Ran 16 tests with 0 failures, 0 errors, 0 skipped in 3 minutes 45.552 seconds.
Tearing down left over layers:
  Tear down plone.app.contenttypes.testing.PloneAppContenttypes:Robot in 0.000 seconds.
  Tear down plone.testing.zope.WSGIServer in 0.007 seconds.
  Tear down plone.app.contenttypes.testing.PloneAppContenttypesRobot in 0.070 seconds.
  Tear down plone.app.robotframework.remote.RemoteLibraryBundle:RobotRemote in 0.000 seconds.
  Tear down plone.app.event.testing.PAEventLayer in 0.011 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.127 seconds.
  Tear down plone.testing.zope.Startup in 0.006 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.002 seconds.
Total: 308 tests, 0 failures, 0 errors, 6 skipped in 5 minutes 10.420 seconds.
❯ ROBOT_BROWSER=chrome  ./bin/test --all -m plone.app.contenttypes
 ~/workspace/buildout.coredev52-py27  5.2 !2                                                                                                                                              INT ✘  plone52 Py  plone52 Py  10.7.0 Node 








```

**Comment by mauritsvanrees** [comment]
I don't know why the Python 2.7 job failed. The change looks clean to me.
I have restarted the job.

**Comment by agitator** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
The master branch is only for Plone 6 now, which currently means you have to start the jobs manually.

**Comment by agitator** [comment]
Thx for the reminder!

Reran the tests to see what went wrong but all links to test details result in a 404, any idea about that?

**Comment by jensens** [comment]
One unrelated failure (unstable robot test). Ready for merge

**Comment by agitator** [comment]
@mauritsvanrees time for release(s)?

**Comment by mauritsvanrees** [comment]
@agitator Is there a rush? There are lots of packages in 6.0 `checkouts.cfg`.

Or do you want this in 5.2? When this PR was created, 5.2 was still using the master branch, but after the merge of the bootstrap stuff, 5.2 uses branch 1.1.x. So this would need to be backported then. Should be okay.

**Comment by agitator** [comment]
I'm using it in 5.2 as well...

Opened https://github.com/plone/plone.batching/pull/29 to cherry pick the changes - could you check it?

**Pull request merged**
