### PR TITLE
Fix issue with orphaning

### PR DESCRIPTION
**Pull request by do3cc**
Orphaning did not work...
Added a test and an assertion for funny folks
trying to have orphan ranges higher than batch size.

### CODE REVIEW

**Comment by saily** [comment]
This seems to break `PloneBatch`, please revert if we should fix this in `plone.batching`.

**Comment by tisto** [comment]
Pull request reverted: https://github.com/plone/plone.batching/pull/5

**Comment by saily** [comment]
@do3cc can you please look into this and reopen the pull?

**Comment by do3cc** [comment]
Uhm, whats the proper way to revert a revert (Once its fixed?) @tisto 
I've read that what once something has been reverted it cant be added properly any more

**Comment by jensens** [comment]
go exact that, press revert  on the revert.

**Pull request merged**
