### PR TITLE
Modernize pagination markup to HTML5 and switches deprecated listingB…

### PR DESCRIPTION
**Pull request by davilima6**
…ar CSS class reference to pagination

### CODE REVIEW

**Comment by davilima6** [comment]
Related to:

* https://github.com/plone/plone.app.layout/pull/76
* https://github.com/plone/plone.app.registry/pull/12
* https://github.com/plone/plonetheme.barceloneta/pull/77

**Comment by thet** [comment]
@davilima6 reviewed, tested and fixed!
please review my changes.
let's wait for the jenkins job to finish.

**Comment by thet** [comment]
The brackets broke the visual design - the spans btw li elements are designed to look like the anchor elements, but the brackets were outside the spans... Of course, that could be solved, but I think, they are not needed. I'd add them with CSS ``:before`` and ``:after`` selectors, I'd want them.

**Comment by thet** [comment]
@hvelarde - as someone concerned about migration issues - do you have an opinion about this?
if ok, plz merge.
it's definitely a step forward, alone that the listing bar is finally styled in plone 5! (wasn't before...)

**Comment by hvelarde** [comment]
:-) just give me some time; I think we have a requirement related with navigation from one of our customers...  I'll be back with some feedback.

**Comment by hvelarde** [comment]
@thet seems that I'm already late but... there is a request for one of our customers of something that seems related with this: usage of `<link rel="prev" href="..." />` and `<link rel="next" href="..." />` on listings and the consequent removal of `<link rel="canonical" href="..." />`; do we open a new issue?

**Comment by hvelarde** [comment]
@agitator please ask always for a squash, when needed, before merging

**Comment by thet** [comment]
I'm not always pro squashing - one, I'd have removed @davilima6 from commit history and second some commits should stand for itself to show the reason of a particular change (but not really in this case).

your suggestion about ``<link rel>`` - that's a different issue / pull request. regarding to https://googlewebmastercentral.blogspot.co.at/2011/09/pagination-with-relnext-and-relprev.html the link elements should be injected into the html/head section. why doesn't your customer want rel="cannonical"? sounds like a good fit.
all in all, i'm not sure, if that's still best practice or is this something google tried to establish couldn't enforce? but this should be discussed in a different issue.

**Comment by hvelarde** [comment]
@thet that's why I said "when needed".

on the other side, you're right about the `<link rel="canonical" href="..." />`, there's no need for removal; I'll create a feature request.

**Comment by thet** [comment]
@hvelarde it's a different issue, but regarding your link next/previous thing: this can be made optional, like the ``ISocialMediaSchema`` controlpanel options. It's even a bit related to that, because it changes visibility to other services (google).

**Comment by hvelarde** [comment]
@thet I don't think it has to be optional; it makes no harm and is common among search engines; I opened a new issue in https://github.com/plone/Products.CMFPlone/issues/1325

**Comment by mauritsvanrees** [comment]
I am making releases. Currently Plone 4 is using the master branch of plone.batching. Since the version number has been bumped to 1.1 and there is an upgrade warning at the top of the changelog file, it seems better to create a maintenance branch 1.0.x for Plone 4, without these changes.

@davilima6 Do you agree?

**Comment by thet** [comment]
@mauritsvanrees I agree. In Plone 4.x only plone.batching < 1.1 should be in. If someone wants - like me - then it's always possbile to use 1.1 in Plone 4.x by explicitly depending on it.

**Comment by davilima6** [comment]
@mauritsvanrees: +1

**Comment by mauritsvanrees** [comment]
Good. I have created branch 1.0.x.
And the changes above are in fresh release 1.1.0.
Thanks for your work on this!

**Comment by davilima6** [comment]
Thank you, @mauritsvanrees. Could you release 1.0.8 today as well or should we better wait Plone 4.3.8 to get closer?

**Comment by mauritsvanrees** [comment]
There are no changes on the 1.0.x branch, except one minor edit in setup.py. So no release is needed.

**Comment by davilima6** [comment]
@mauritsvanrees Actually I believe this commit b0a56733ecd79fedacfd22159ba3c25b0ca9ab46 should have been the tip for 1.0.x branch. as explained in https://github.com/plone/plone.batching/pull/14#issuecomment-170643861. Should I just cherry-pick it there or would you recommend anything else?

**Comment by thet** [comment]
@davilima6 right. It's mentioned in the 1.0.8 section of the CHANGES.rst file in the master branch: https://github.com/plone/plone.batching/blob/master/CHANGES.rst

**Comment by mauritsvanrees** [comment]
Ah, I wasn't aware of that separate pull request. I will cherry-pick the commit and release 1.0.8 for Plone 4.3.

**Comment by mauritsvanrees** [comment]
1.0.8 released.

**Comment by davilima6** [comment]
Thank you :+1:

**Pull request merged**
