### PR TITLE
cherry pick changes from https://github.com/plone/plone.batching/pull/26

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

One Jenkins failure, which I have restarted, but I guess this is a flaky test.

**Comment by mauritsvanrees** [comment]
Yep, flaky test, and now another one is flaky. I will merge.

**Comment by agitator** [comment]
thx, do you think this could/should make it into 5.2.4?

**Comment by mauritsvanrees** [comment]
Yes. I have released 1.1.7 and have added it to https://dist.plone.org/release/5.2.4-pending/versions.cfg

**Pull request merged**
