### PR TITLE
doc reformat, pep8

### PR DESCRIPTION
**Pull request by thet**
- Documentation reformat.
- PEP 8, UTF 8 headers.

### CODE REVIEW

**Comment by thet** [comment]
@svx @jensens

**Comment by thet** [comment]
@svx @jensens same question like here: https://github.com/plone/plone.memoize/pull/2
the interesting doctest files are:
https://github.com/plone/plone.batching/blob/thet-reformat/plone/batching/usage.rst
https://github.com/plone/plone.batching/blob/thet-reformat/plone/batching/batching.rst

**Comment by jensens** [comment]
however, this PR can be merged, including it is a papyrus thing i suppose

**Comment by mauritsvanrees** [comment]
I have released plone.batching 1.0.6 with this.  But then the coredev tests are failing: the plone.batching tests fail to find `../../docs/usage.rst`.  See http://jenkins.plone.org/job/plone-5.0-python-2.7/3601/console

Can you have a look at that?

The 1.0.6 release itself is fine for daily use.  But I have added it to the checkouts.cfg again in coredev 4.3 and 5.0, which will fix Jenkins.

**Comment by jensens** [comment]
ping @thet

**Comment by thet** [comment]
I'm wondering, why this happens. I can reproduce the problem, when checked out as egg. The test.py doesn't have access to the docs folder.
I commented out the problematic line. Now it should work. Please re-release plone.batching with it.

**Comment by mauritsvanrees** [comment]
But then we no longer execute this doctest, and this part of the documentation will be untested...

Well, I guess that is what you get when we want to have the documentation in the docs directory. And symlinks would only give different problems. And no one would complain about this if usage.rst would contain no `>>> testable python code`. :-)

So I will release.

**Comment by mauritsvanrees** [comment]
Done: 1.0.7.

**Pull request merged**
